In [1]:
import numpy as np
import sympy as sym
import matplotlib as plt

In [2]:
# ЗАДАНИЕ 1
# Создайте матрицу 3 на 3, заполненную числами от 1 до 9
A1 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
A2 = np.eye(3)


In [6]:
# Прибавьте к ней матрицу с единицами на диагонале
A3=A1+A2
A3

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [8]:
# Умножьте полученную матрицу на вектор (1, 2, 3)
Vec_A=np.array([1,2,3])
A4=A3@Vec_A
A4

array([15., 34., 53.])

In [10]:
# Вычислить транспонированную матрицу от полученной в результате прибавления матрицы
A3_t=np.transpose(A3)
A3_t

array([[ 2.,  4.,  7.],
       [ 2.,  6.,  8.],
       [ 3.,  6., 10.]])

In [15]:
# Посчитайте обратную матрицу к полученной в результате прибавления матрице
A3_inv=np.linalg.inv(A3)
A3_inv

array([[-6.00000000e+00, -2.00000000e+00,  3.00000000e+00],
       [-1.00000000e+00,  5.00000000e-01,  5.44009282e-16],
       [ 5.00000000e+00,  1.00000000e+00, -2.00000000e+00]])

In [16]:
# Значения получились значительно меньше нуля, обратной матрицы не существует
A3_inv@A3 # в итоге перемножения мы не получили единичную матрицу, следовательно утверждение верно

array([[1.00000000e+00, 0.00000000e+00, 8.88178420e-16],
       [4.77395901e-16, 1.00000000e+00, 2.22044605e-16],
       [6.66133815e-16, 0.00000000e+00, 1.00000000e+00]])

In [19]:
# ЗАДАНИЕ 2
# Найдите собственные значения и собственные вектора матрицы:
m = np.array([[2, 2],
              [1, 3]])
print(m)
np.linalg.eigvals(m) # собственные значения матрицы
np.linalg.eig(m) # собственные векторы матрицы

[[2 2]
 [1 3]]


(array([1., 4.]),
 array([[-0.89442719, -0.70710678],
        [ 0.4472136 , -0.70710678]]))

In [88]:
# ЗАДАНИЕ 3
# Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.
# P.S. Матрица должна быть ненулевой и размерностью не менее 2!
A_uno=([[1, 2, 1], [1, 2, 2], [1, 1, 2]]) # за основу взята матрица с рангом 3
np.linalg.det(A_uno)

1.0